apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv-volume
  labels:
    type: {{ .Values.pv.type }}
    name: wp-nfs-vol
spec:
  capacity:
    storage: {{ .Values.pv.storage }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ .Values.nfs_path_sa }}
    server: {{ .Values.nfs_server_sa }}
