---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
  selector:
    matchLabels:
      name: wp-nfs-vol
      type: {{ .Values.pvc.type }}
